## Introducción

En estos ejercicios vamos a trabajar con los datasets alojado en la ruta del curso **/Dia-05/datasets/XXVideos** representan el conjunto de estadísticas de vídeos de Youtube en los países de Canadá, USA y México.

Las columnas del dataframe significan lo siguiente:

1. `video_id` : Id del vídeo
2. `trending_date` : Fecha de registro de estadísticas
3. `title` : Título del vídeo
4. `channel_title` : Nombre del canal de Youtube
5. `category_id` : Id de la categoría del vídeo
6. `publish_time` : Fecha de publicación del vídeo
7. `tags` : Etiquetas del vídeo
8. `views` : Vistas del vídeo en la fecha 'trending_date'
9. `likes` : Likes del video en la fecha 'trending_date'
10. `dislikes` : Dislikes del video en la fecha 'trending_date'
11. `comment_count` : Número de comentarios en la fecha 'trending_date'
12. `thumbnail_link` : Link a la miniatura del vídeo
13. `comments_disabled` : Comentarios desactivados
14. `ratings_disabled` : Likes/Dislikes desactivados
15. `video_error_or_removed` : Video borrado o con error en subida
16. `description` : Descripción del vídeo

Ejecuta la siguiente celda para el dataframe con el contenido del dataset.

In [36]:
import pandas as pd 

ca_videos = pd.read_csv("./datasets/CAvideos.csv")
mx_videos = pd.read_csv("./datasets/MXvideos.csv", encoding ='latin-1')
usa_videos = pd.read_csv("./datasets/usvideos.csv")

## Ejercicio 1

Imprime los tipos de datos de las columnas de los 3 dataframes. ¿Tienen los mismos tipos de datos?

In [37]:
print('Tipos de datos CA:')
print(ca_videos.dtypes)

Tipos de datos CA:
video_id                    str
trending_date               str
title                       str
channel_title               str
category_id               int64
publish_time                str
tags                        str
views                     int64
likes                     int64
dislikes                  int64
comment_count             int64
thumbnail_link              str
comments_disabled          bool
ratings_disabled           bool
video_error_or_removed     bool
description                 str
dtype: object

In [38]:
print('\nTipos de datos MX:')
print(mx_videos.dtypes)

Tipos de datos MX:
video_id                    str
trending_date               str
title                       str
channel_title               str
category_id               int64
publish_time                str
tags                        str
views                     int64
likes                     int64
dislikes                  int64
comment_count             int64
thumbnail_link              str
comments_disabled          bool
ratings_disabled           bool
video_error_or_removed     bool
description                 str
dtype: object

In [39]:
print('\nTipos de datos USA:')
print(usa_videos.dtypes)

Tipos de datos USA:
video_id                    str
trending_date               str
title                       str
channel_title               str
category_id               int64
publish_time                str
tags                        str
views                     int64
likes                     int64
dislikes                  int64
comment_count             int64
thumbnail_link              str
comments_disabled          bool
ratings_disabled           bool
video_error_or_removed     bool
description                 str
dtype: object

In [40]:
comprobar_datos = ca_videos.dtypes.equals(mx_videos.dtypes) and ca_videos.dtypes.equals(usa_videos.dtypes)
print(f'Los tres dataframes tienen los mismos tipos de datos? {comprobar_datos}')

Los tres dataframes tienen los mismos tipos de datos? True

## Ejercicio 2 

Renombra las columnas `trending_date` y `publish_time` a los nombres `statistics_date` y `publish_date` respectivamente para los 3 paises.

In [41]:
ca_videos = ca_videos.rename(columns={'trending_date': 'statistics_date', 'publish_time': 'publish_date'})
mx_videos = mx_videos.rename(columns={'trending_date': 'statistics_date', 'publish_time': 'publish_date'})
usa_videos = usa_videos.rename(columns={'trending_date': 'statistics_date', 'publish_time': 'publish_date'})

display(ca_videos.head())
display(mx_videos.head())
display(usa_videos.head())

,video_id,statistics_date,title,channel_title,category_id,publish_date,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...

,video_id,statistics_date,title,channel_title,category_id,publish_date,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,SbOwzAl9ZfQ,17.14.11,CapÃ­tulo 12 | MasterChef 2017,MasterChef 2017,24,2017-11-13T06:06:22.000Z,"MasterChef Junior 2017|""TV Azteca""|""recetas""|""...",310130,4182,361,1836,https://i.ytimg.com/vi/SbOwzAl9ZfQ/default.jpg,False,False,False,Disfruta la presencia del Chef Torreblanca en ...
1,klOV6Xh-DnI,17.14.11,ALEXA EX-INTEGRANTE DEL GRUPO TIMBIRICHE RENUN...,Micky Contreras Martinez,22,2017-11-13T05:11:58.000Z,La Voz Mexico 7,104972,271,174,369,https://i.ytimg.com/vi/klOV6Xh-DnI/default.jpg,False,False,False,ALEXA EX-INTEGRANTE DEL GRUPO TIMBIRICHE RENUN...
2,6L2ZF7Qzsbk,17.14.11,LOUIS CKAGÃ - EL PULSO DE LA REPÃBLICA,El Pulso De La RepÃºblica,25,2017-11-13T17:00:02.000Z,"Chumel Torres|""El Pulso de la Republica""|""noti...",136064,10105,266,607,https://i.ytimg.com/vi/6L2ZF7Qzsbk/default.jpg,False,False,False,La canciÃ³n del principio se llama âEste esp...
3,hcY52MFWMDM,17.14.11,Sismo de 6.7 sacude Costa Rica 12 Noviembre 2017,Casanare,25,2017-11-13T03:47:10.000Z,"temblor|""costa rica""|""sismo en costa rica""",96153,378,171,208,https://i.ytimg.com/vi/hcY52MFWMDM/default.jpg,False,False,False,El video es de un Walmart en el pais centroame...
4,_OXDcGPVAa4,17.14.11,DOG HACKS | MUSAS LESSLIE LOS POLINESIOS,Musas,26,2017-11-13T19:17:48.000Z,"MUSAS|""lesslie""|""karen""|""hacks""|""perros""|""dogs...",499965,57781,681,7428,https://i.ytimg.com/vi/_OXDcGPVAa4/default.jpg,False,False,False,MI HERMANO NARRA MI RUTINA DE MAQUILLAJE\nhttp...

,video_id,statistics_date,title,channel_title,category_id,publish_date,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13T17:13:01.000Z,SHANtell martin,748374,57527,2966,15954,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...
1,1ZAPwfrtAFY,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13T07:30:00.000Z,"last week tonight trump presidency|""last week ...",2418783,97185,6146,12703,https://i.ytimg.com/vi/1ZAPwfrtAFY/default.jpg,False,False,False,"One year after the presidential election, John..."
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146033,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...
3,puqaWrEC7tY,17.14.11,Nickelback Lyrics: Real or Fake?,Good Mythical Morning,24,2017-11-13T11:00:04.000Z,"rhett and link|""gmm""|""good mythical morning""|""...",343168,10172,666,2146,https://i.ytimg.com/vi/puqaWrEC7tY/default.jpg,False,False,False,Today we find out if Link is a Nickelback amat...
4,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095731,132235,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...

## Ejercicio 3

Convierte las columnas `statistics_date` y `publish_date` de los 3 dataframe tipo de dato datetime64 con el formato **YYYY-MM-DD** para poder realizar funciones de agrupación y extracción de fechas.Consulta sobre strftime para esto

In [42]:
ca_videos['statistics_date'] = pd.to_datetime(ca_videos['statistics_date'], format='%y.%d.%m')
mx_videos['statistics_date'] = pd.to_datetime(mx_videos['statistics_date'], format='%y.%d.%m')
usa_videos['statistics_date'] = pd.to_datetime(usa_videos['statistics_date'], format='%y.%d.%m')

ca_videos['publish_date'] = pd.to_datetime(ca_videos['publish_date'])
mx_videos['publish_date'] = pd.to_datetime(mx_videos['publish_date'])
usa_videos['publish_date'] = pd.to_datetime(usa_videos['publish_date'])

print(ca_videos.dtypes)
print(mx_videos.dtypes)
print(usa_videos.dtypes)

video_id                                  str
statistics_date                datetime64[us]
title                                     str
channel_title                             str
category_id                             int64
publish_date              datetime64[us, UTC]
tags                                      str
views                                   int64
likes                                   int64
dislikes                                int64
comment_count                           int64
thumbnail_link                            str
comments_disabled                        bool
ratings_disabled                         bool
video_error_or_removed                   bool
description                               str
dtype: object
video_id                                  str
statistics_date                datetime64[us]
title                                     str
channel_title                             str
category_id                             int64
publish_date              datetime64[us, UTC]
tags                                      str
views                                   int64
likes                                   int64
dislikes                                int64
comment_count                           int64
thumbnail_link                            str
comments_disabled                        bool
ratings_disabled                         bool
video_error_or_removed                   bool
description                               str
dtype: object
video_id                                  str
statistics_date                datetime64[us]
title                                     str
channel_title                             str
category_id                             int64
publish_date              datetime64[us, UTC]
tags                                      str
views                                   int64
likes                                   int64
dislikes                                int64
comment_count                           int64
thumbnail_link                            str
comments_disabled                        bool
ratings_disabled                         bool
video_error_or_removed                   bool
description                               str
dtype: object

## Ejercicio 4

¿En que año se subieron más vídeos para cada país? 

**Ten en cuenta que puede haber más de una fila que compartan el mismo video (`video_id`)**

In [43]:
# CANADÁ
videos_unicos_ca = ca_videos.drop_duplicates(subset='video_id')
anio_mas_videos_ca = videos_unicos_ca['publish_date'].dt.year.value_counts().idxmax()

# MEXICO
videos_unicos_mx = mx_videos.drop_duplicates(subset='video_id')
anio_mas_videos_mx = videos_unicos_mx['publish_date'].dt.year.value_counts().idxmax()

# ESTADOS UNIDOS
videos_unicos_usa = usa_videos.drop_duplicates(subset='video_id')
anio_mas_videos_usa = videos_unicos_usa['publish_date'].dt.year.value_counts().idxmax()

In [44]:
print('Año con más videos publicados por país:')
print(f'\tCanadá: {anio_mas_videos_ca}')
print(f'\tMéxico: {anio_mas_videos_mx}')
print(f'\tEstados Unidos: {anio_mas_videos_usa}')

Año con más videos publicados por país:
	Canadá: 2018
	México: 2018
	Estados Unidos: 2018

## Ejercicio 5 

¿Qué mes del año 2017 tiene el record en visitas para el dataframe de vídeos de México?

In [45]:
videos_2017_mx = mx_videos[mx_videos['publish_date'].dt.year == 2017]

mes_mas_vistas = videos_2017_mx.groupby(videos_2017_mx['publish_date'].dt.month)['views'].sum().idxmax()

In [46]:
meses = {1: 'Enero', 
         2: 'Febrero', 
         3: 'Marzo', 
         4: 'Abril', 
         5: 'Mayo', 
         6: 'Junio', 
         7: 'Julio', 
         8: 'Agosto', 
         9: 'Septiembre', 
         10: 'Octubre', 
         11: 'Noviembre', 
         12: 'Diciembre'}

print(f'El mes con más vistas en 2017 en México es: {meses[mes_mas_vistas]}')

El mes con más vistas en 2017 en México es: Diciembre

## Ejercicio 6

¿Qué dataframe de los 3 tiene más valores nulos entre todas sus columnas? Calcula el porcentaje de columnas nulas de los dataframes utilizando la función `apply`

In [47]:
porcentaje_nulos_ca = ca_videos.apply(lambda col: col.isnull().mean() * 100).mean()
porcentaje_nulos_mx = mx_videos.apply(lambda col: col.isnull().mean() * 100).mean()
porcentaje_nulos_usa = usa_videos.apply(lambda col: col.isnull().mean() * 100).mean()

print(f'Porcentaje de nulos en CA: {round(porcentaje_nulos_ca, 2)}%')
print(f'Porcentaje de nulos en MX: {round(porcentaje_nulos_mx, 2)}%')
print(f'Porcentaje de nulos en USA: {round(porcentaje_nulos_usa, 2)}%')

if porcentaje_nulos_ca > porcentaje_nulos_mx and porcentaje_nulos_ca > porcentaje_nulos_usa:
    dataframe_mas_nulos = 'CA'
elif porcentaje_nulos_mx > porcentaje_nulos_usa:
    dataframe_mas_nulos = 'MX'
else:
    dataframe_mas_nulos = 'USA'

print(f'El dataframe con más nulos es: {dataframe_mas_nulos}')

Porcentaje de nulos en CA: 0.2%
Porcentaje de nulos en MX: 0.65%
Porcentaje de nulos en USA: 0.09%
El dataframe con más nulos es: MX

## Ejercicio 7

Reemplaza los valores nulos del dataframe con más valores nulos con los siguientes criterios:

- 1. Si la columna es de tipo int64 reemplaza el valor nulo por la moda de valores de esa columna. (La moda es el valor que más se repite dentro de los valores de la columna.)
- 2. Si la columna es de tipo string rellena cada valor nulo por el valor no nulo más próximo después de ese registro. (Estrategia de relleno)

In [52]:
df = mx_videos

for columna in df.columns:
    if df[columna].dtype == 'int64':
        moda_columna = df[columna].mode()[0]
        df[columna] = df[columna].fillna(moda_columna)
    else:
        df[columna] = df[columna].bfill()

## Ejercicio 8

¿Cuántos vídeos tienen audiciencia compartida entre los 3 dataframes? Es decir, que se hayan visto en USA, Canadá y México. 

**Puedes combinar los dataframes por la columna `video_id`**

In [54]:
videos_comunes = set(ca_videos['video_id']) & set(mx_videos['video_id']) & set(usa_videos['video_id'])

print(f'Cantidad de videos con audiencia compartida: {len(videos_comunes)}')

Cantidad de videos con audiencia compartida: 509

## Ejercicio 9

¿Cuál es el vídeo más visto que se vió en los 3 países? ¿Y el que tuvo más likes?

In [57]:
ca_comunes = ca_videos[ca_videos['video_id'].isin(videos_comunes)]
mx_comunes = mx_videos[mx_videos['video_id'].isin(videos_comunes)]
usa_comunes = usa_videos[usa_videos['video_id'].isin(videos_comunes)]

video_mas_visto_ca = ca_comunes.sort_values(by='views', ascending=False).iloc[0]
video_mas_visto_mx = mx_comunes.sort_values(by='views', ascending=False).iloc[0]
video_mas_visto_usa = usa_comunes.sort_values(by='views', ascending=False).iloc[0]

video_mas_likes_ca = ca_comunes.sort_values(by='likes', ascending=False).iloc[0]
video_mas_likes_mx = mx_comunes.sort_values(by='likes', ascending=False).iloc[0]
video_mas_likes_usa = usa_comunes.sort_values(by='likes', ascending=False).iloc[0]

print('VIDEO MÁS VISTO POR PAÍS')
print(f'\tCanadá: {video_mas_visto_ca["title"]}')
print(f'\tMéxico: {video_mas_visto_mx["title"]}')
print(f'\tUSA: {video_mas_visto_usa["title"]}')

print('\nVIDEO CON MÁS LIKES POR PAÍS')
print(f'\tCanadá: {video_mas_likes_ca["title"]}')
print(f'\tMéxico: {video_mas_likes_mx["title"]}')
print(f'\tUSA: {video_mas_likes_usa["title"]}')

VIDEO MÁS VISTO POR PAÍS
	Canadá: YouTube Rewind: The Shape of 2017 | #YouTubeRewind
	México: YouTube Rewind: The Shape of 2017 | #YouTubeRewind
	USA: Childish Gambino - This Is America (Official Video)

VIDEO CON MÁS LIKES POR PAÍS
	Canadá: BTS (방탄소년단) 'FAKE LOVE' Official MV
	México: BTS (ë°©íìëë¨) 'FAKE LOVE' Official MV
	USA: BTS (방탄소년단) 'FAKE LOVE' Official MV